services:
  - type: web
    name: hozrgikod-bot
    runtime: python
    repo: https://github.com/biloldinn/hozrgikod
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python forward_bot.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
